global:
  domain: "semaphore.mrops.com.br"
  basePath: "/semaphoreUI"

semaphore:
  image:
    tag: "v2.10.0"
  oidc:
    enabled: true
    providerUrl: "https://auth.mrops.com.br/realms/mrops-base"
    baseUrl: "https://semaphore.mrops.com.br/semaphoreUI"
    vaultPath: "semaphore/ui-nginx/dev/credentials"
  admin:
    username: "admin"
    password: "admin"
    email: "admin@mrops.com.br"
    name: "Admin"
  persistence:
    size: 1Gi
    storageClass: "local-path"

ingress:
  enabled: true
  hosts:
    - host: "semaphore.mrops.com.br"
