apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semaphore-ui.fullname" . }}-semaphore-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphore-ui.semaphore.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  SEMAPHORE_ADMIN:                 {{ .Values.semaphore.admin.username | quote }}
  SEMAPHORE_ADMIN_PASSWORD:        {{ .Values.semaphore.admin.password | quote }}
  SEMAPHORE_ADMIN_EMAIL:           {{ .Values.semaphore.admin.email | quote }}
  SEMAPHORE_ADMIN_NAME:            {{ .Values.semaphore.admin.name | quote }}
  SEMAPHORE_COOKIE_HASH:           {{ .Values.semaphore.config.cookieHash | default (randAlphaNum 32) | quote }}
  SEMAPHORE_COOKIE_ENCRYPTION:     {{ .Values.semaphore.config.cookieEncryption | default (randAlphaNum 32) | quote }}
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: {{ .Values.semaphore.config.accessKeyEncryption | default (randAlphaNum 32) | quote }}
