apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semaphore-ui.fullname" . }}-semaphore-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphore-ui.semaphore.labels" . | nindent 4 }}
data:
  SEMAPHORE_DB_DIALECT:    {{ .Values.semaphore.config.dbDialect | quote }}
  SEMAPHORE_DB_PATH:       {{ .Values.semaphore.config.dbPath | quote }}
  SEMAPHORE_WEB_HOST:      {{ printf "https://%s" .Values.global.domain | quote }}
  SEMAPHORE_WEB_ROOT:      {{ .Values.global.basePath | quote }}
  SEMAPHORE_PORT:          {{ printf ":%v" .Values.semaphore.service.port | quote }}
  SEMAPHORE_TMP_PATH:      "/tmp/semaphore"
  SEMAPHORE_LDAP_ACTIVATED: {{ .Values.semaphore.config.ldapEnabled | quote }}
  {{- if .Values.semaphore.config.emailSender }}
  SEMAPHORE_EMAIL_SENDER:  {{ .Values.semaphore.config.emailSender | quote }}
  {{- end }}
  {{- if .Values.semaphore.config.emailHost }}
  SEMAPHORE_EMAIL_HOST:    {{ .Values.semaphore.config.emailHost | quote }}
  {{- end }}
  {{- if .Values.semaphore.config.emailPort }}
  SEMAPHORE_EMAIL_PORT:    {{ .Values.semaphore.config.emailPort | quote }}
  {{- end }}
