{{- if .Values.semaphore.oidc.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "semaphore-ui.fullname" . }}-semaphore-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphore-ui.semaphore.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.semaphore.oidc.vaultPath }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.semaphore.oidc.vaultPath }}
        property: client_secret
  target:
    name: {{ include "semaphore-ui.fullname" . }}-semaphore-oidc
    template:
      engineVersion: v2
      data:
        SEMAPHORE_OIDC_PROVIDERS: |
          {
            "{{ .Values.semaphore.oidc.providerKey }}": {
              "display_name": "{{ .Values.semaphore.oidc.displayName }}",
              "color": "{{ .Values.semaphore.oidc.color }}",
              "icon": "{{ .Values.semaphore.oidc.icon }}",
              "provider_url": "{{ .Values.semaphore.oidc.providerUrl }}",
              "client_id": "{{ "{{" }} .client_id }}",
              "client_secret": "{{ "{{" }} .client_secret }}",
              "redirect_url": "{{ .Values.semaphore.oidc.baseUrl }}/api/auth/oidc/{{ .Values.semaphore.oidc.providerKey }}/redirect"
            }
          }
{{- end }}
