---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "semaphore-ui.semaphore.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphore-ui.semaphore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.semaphore.service.type }}
  selector:
    {{- include "semaphore-ui.semaphore.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.semaphore.service.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "semaphore-ui.nginx.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphore-ui.nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "semaphore-ui.nginx.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
